#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/bi_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2025.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2023.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2024.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2025.nc 
